telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

spring:
  datasource:
    url: ${POSTGRESQL_JDBC_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
description:
  start: "Welcome to TrackMyCoin 📈💰!
          \n\nThis bot helps you track cryptocurrency prices
          and will send you notifications when your target price 
          is reached.
          \n\nFor more information about the bot, type /info."
  info: "TrackMyCoin — your crypto assistant 📈💰!
  
         \nEasily track cryptocurrency prices and get notified
         when your target price is reached.
         \nPerfect for traders and crypto enthusiasts!
  
         \nType /help for a list of all commands."
  help: "List of commands 👾\nInfo -> /info\nHelp -> /help"
  non_command: "non command /help "